#pragma once

#define ANSI_TEXT_RESET               "\x1b[0m"
#define ANSI_TEXT_BOLD                "\x1b[1m"
#define ANSI_TEXT_RESET_BOLD          "\x1b[22m"
#define ANSI_TEXT_DIM                 "\x1b[2m"
#define ANSI_TEXT_RESET_DIM           "\x1b[22m"
#define ANSI_TEXT_ITALIC              "\x1b[3m"
#define ANSI_TEXT_RESET_ITALIC        "\x1b[23m"
#define ANSI_TEXT_UNDERLINE           "\x1b[4m"
#define ANSI_TEXT_RESET_UNDERLINE     "\x1b[24m"
#define ANSI_TEXT_BLINK               "\x1b[5m"
#define ANSI_TEXT_RESET_BLINK         "\x1b[25m"
#define ANSI_TEXT_INVERSE             "\x1b[7m"
#define ANSI_TEXT_RESET_INVERSE       "\x1b[27m"
#define ANSI_TEXT_HIDDEN              "\x1b[8m"
#define ANSI_TEXT_RESET_HIDDEN        "\x1b[28m"
#define ANSI_TEXT_STRIKETHROUGH       "\x1b[9m"
#define ANSI_TEXT_RESET_STRIKETHROUGH "\x1b[29m"

#define ANSI_ERASE_IN_DISPLAY                    "\x1b[J"
#define ANSI_ERASE_FROM_CURSOR_TO_SCREEN_END     "\x1b[0J"
#define ANSI_ERASE_FROM_CURSOR_TO_SCREEN_START   "\x1b[1J"
#define ANSI_ERASE_SCREEN                        "\x1b[2J"
#define ANSI_ERASE_SAVED_LINES                   "\x1b[3J"
#define ANSI_ERASE_IN_LINE                       "\x1b[K"
#define ANSI_ERASE_FROM_CURSOR_TO_LINE_END       "\x1b[0K"
#define ANSI_ERASE_FROM_CURSOR_TO_LINE_START     "\x1b[1K"
#define ANSI_ERASE_LINE                          "\x1b[2K"

#define ANSI_COLOR_FG_BLACK   "\x1b[30m"
#define ANSI_COLOR_FG_RED     "\x1b[31m"
#define ANSI_COLOR_FG_GREEN   "\x1b[32m"
#define ANSI_COLOR_FG_YELLOW  "\x1b[33m"
#define ANSI_COLOR_FG_BLUE    "\x1b[34m"
#define ANSI_COLOR_FG_MAGENTA "\x1b[35m"
#define ANSI_COLOR_FG_CYAN    "\x1b[36m"
#define ANSI_COLOR_FG_WHITE   "\x1b[37m"
#define ANSI_COLOR_FG_DEFAULT "\x1b[39m"

#define ANSI_COLOR_BG_BLACK   "\x1b[40m"
#define ANSI_COLOR_BG_RED     "\x1b[41m"
#define ANSI_COLOR_BG_GREEN   "\x1b[42m"
#define ANSI_COLOR_BG_YELLOW  "\x1b[43m"
#define ANSI_COLOR_BG_BLUE    "\x1b[44m"
#define ANSI_COLOR_BG_MAGENTA "\x1b[45m"
#define ANSI_COLOR_BG_CYAN    "\x1b[46m"
#define ANSI_COLOR_BG_WHITE   "\x1b[47m"
#define ANSI_COLOR_BG_DEFAULT "\x1b[49m"
